-- NON EVENT CINEMAS — named recommendation votes
-- Run this ONCE in Supabase > SQL Editor.
--
-- Why this exists:
-- The existing toggle_recommendation_vote RPC knows how to change the numeric
-- vote total, but the public recommendations query does not expose the voter
-- usernames. This companion table records the names for display/pressed state.

create table if not exists public.recommendation_vote_names (
  id bigint generated by default as identity primary key,
  recommendation_id uuid not null
    references public.recommendations(id) on delete cascade,
  user_name text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists one_named_vote_per_user_per_recommendation
on public.recommendation_vote_names (
  recommendation_id,
  lower(trim(user_name))
);

alter table public.recommendation_vote_names enable row level security;

drop policy if exists "named votes readable" on public.recommendation_vote_names;
create policy "named votes readable"
on public.recommendation_vote_names
for select
to anon, authenticated
using (true);

drop policy if exists "named votes insertable" on public.recommendation_vote_names;
create policy "named votes insertable"
on public.recommendation_vote_names
for insert
to anon, authenticated
with check (true);

drop policy if exists "named votes removable" on public.recommendation_vote_names;
create policy "named votes removable"
on public.recommendation_vote_names
for delete
to anon, authenticated
using (true);

-- New rule: nominating a film includes your own vote.
-- We can safely identify the nominator for old recommendations, even though
-- other historical voter identities cannot be reconstructed from a count.
insert into public.recommendation_vote_names (recommendation_id, user_name)
select id, trim(user_name)
from public.recommendations
where is_active = true
  and nullif(trim(user_name), '') is not null
on conflict do nothing;

-- Preserve all existing totals, but make sure every active nomination has
-- at least the nominator's one automatic vote.
update public.recommendations
set votes = greatest(coalesce(votes, 0), 1)
where is_active = true
  and nullif(trim(user_name), '') is not null;
