-- NON EVENT CINEMAS
-- Paste this whole file into Supabase > SQL Editor > New query > Run.

create table if not exists public.screenings (
  id bigint generated by default as identity primary key,
  title text not null,
  screening_at timestamptz not null,
  runtime text,
  year int,
  note text,
  poster_url text,
  curator text,
  is_past boolean not null default false,
  is_cancelled boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  screening_id bigint not null references public.screenings(id) on delete cascade,
  user_name text not null check (char_length(user_name) between 1 and 24),
  status text not null check (status in ('going','maybe','not_going')),
  created_at timestamptz not null default now(),
  unique(screening_id, user_name)
);

create table if not exists public.recommendations (
  id bigint generated by default as identity primary key,
  title text not null,
  reason text,
  poster_url text,
  user_name text not null check (char_length(user_name) between 1 and 24),
  votes int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.recommendation_votes (
  recommendation_id bigint not null references public.recommendations(id) on delete cascade,
  user_name text not null,
  created_at timestamptz not null default now(),
  primary key (recommendation_id, user_name)
);

create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  screening_id bigint not null references public.screenings(id) on delete cascade,
  user_name text not null check (char_length(user_name) between 1 and 24),
  score int not null check (score between 1 and 5),
  created_at timestamptz not null default now(),
  unique(screening_id, user_name)
);

alter table public.screenings add column if not exists curator text;
alter table public.screenings add column if not exists is_cancelled boolean not null default false;
alter table public.recommendations add column if not exists is_active boolean not null default true;

alter table public.screenings enable row level security;
alter table public.rsvps enable row level security;
alter table public.recommendations enable row level security;
alter table public.recommendation_votes enable row level security;
alter table public.ratings enable row level security;

-- This site intentionally uses lightweight name/initial-based access, not real authentication.
-- These policies allow your friends to read/write through the public anon key.
drop policy if exists "public screenings read" on public.screenings;
create policy "public screenings read" on public.screenings for select using (true);
drop policy if exists "public screenings write" on public.screenings;
drop policy if exists "admin screenings write" on public.screenings;
create policy "admin screenings write"
on public.screenings
for all
to authenticated
using (true)
with check (true);

drop policy if exists "public rsvp read" on public.rsvps;
create policy "public rsvp read" on public.rsvps for select using (true);
drop policy if exists "public rsvp write" on public.rsvps;
create policy "public rsvp write" on public.rsvps for all using (true) with check (true);

drop policy if exists "public recommendations read" on public.recommendations;
create policy "public recommendations read" on public.recommendations for select using (true);
drop policy if exists "public recommendations write" on public.recommendations;
create policy "public recommendations write" on public.recommendations for insert with check (true);

drop policy if exists "public recommendation votes read" on public.recommendation_votes;
create policy "public recommendation votes read" on public.recommendation_votes for select using (true);
drop policy if exists "public recommendation votes write" on public.recommendation_votes;
create policy "public recommendation votes write" on public.recommendation_votes for all using (true) with check (true);

drop policy if exists "public ratings read" on public.ratings;
create policy "public ratings read" on public.ratings for select using (true);
drop policy if exists "public ratings write" on public.ratings;
create policy "public ratings write" on public.ratings for all using (true) with check (true);

create or replace function public.toggle_recommendation_vote(rec_id bigint, voter_name text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.recommendations
    where id = rec_id and is_active = true
  ) then
    return;
  end if;

  if exists (
    select 1 from public.recommendation_votes
    where recommendation_id = rec_id and user_name = voter_name
  ) then
    delete from public.recommendation_votes
    where recommendation_id = rec_id and user_name = voter_name;
  else
    insert into public.recommendation_votes(recommendation_id, user_name)
    values (rec_id, voter_name);
  end if;

  update public.recommendations
  set votes = (
    select count(*) from public.recommendation_votes
    where recommendation_id = rec_id
  )
  where id = rec_id and is_active = true;
end;
$$;

grant execute on function public.toggle_recommendation_vote(bigint, text) to anon;

-- Demo programme. Replace these in Supabase Table Editor with your real movie nights.
insert into public.screenings (title, screening_at, runtime, year, note, poster_url, curator, is_past, is_cancelled)
values
  ('TBC', '2026-10-01 19:30:00+01', null, null, null, null, null, false, false),
  ('Master and Commander', '2026-08-15 19:30:00+01', '2h 18m', 2003, null, 'https://www.impawards.com/2003/posters/master_and_commander.jpg', 'KJ', true, false),
  ('Hot Fuzz', '2026-08-22 19:30:00+01', '2h 1m', 2007, null, 'https://www.impawards.com/2007/posters/hot_fuzz.jpg', 'MG', true, false),
  ('The Grand Budapest Hotel', '2026-08-29 19:30:00+01', '1h 39m', 2014, null, 'https://www.impawards.com/2014/posters/grand_budapest_hotel.jpg', 'BT', true, false);


-- Default programme cadence:
-- Every second Thursday starting 1 October 2026.
-- Voting closes in the website 48 hours before each screening.
-- Use admin.html to create the next fortnightly date, override dates, and confirm films.


-- Public visitors can read screenings. Only authenticated admin users can change them.
grant select on public.screenings to anon;
revoke insert, update, delete on public.screenings from anon;
grant select, insert, update, delete on public.screenings to authenticated;
